package com.magic.domain;

import java.util.Date;

import lombok.Data;

@Data
public class TermData {
	private Date historyDate;
	private int term1;
	private int term2;
	private int term3;
	private int term4;
	private int term5;
	private int term6;
	private int term7;
	private int term8;
	private int term9;
	private int term10;
	private int term11;
	private int term12;
	private int term13;
	private int term14;
	private int term15;
	private int term16;
	private int term17;
	private int term18;
	private int term19;
	private int term20;
	private int term21;
	private int term22;
	private int term23;
	private int term24;
	private int term25;
	private int term26;
	private int term27;
	private int term28;
	private int term29;
	private int term30;
	private int term31;
	private int term32;
	private int term33;
	private int term34;
	private int term35;
	private int term36;
	private int term37;
	private int term38;
	private int term39;
	private int term40;
	private int term41;
	private int term42;
	private int term43;
	private int term44;
	private int term45;
	private int term46;
	private int term47;
	private int term48;
	private int term49;
	private int term50;
	private int term51;
	private int term52;
	private int term53;
	private int term54;
	private int term55;
	private int term56;
	private int term57;
	private int term58;
	private int term59;
	private int term60;
	private int term61;
	private int term62;
	private int term63;
	private int term64;
	private int term65;
	private int term66;
	private int term67;
	private int term68;
	private int term69;
	private int term70;
	private int term71;
	private int term72;
	private int term73;
	private int term74;
	private int term75;
	private int term76;
	private int term77;
	private int term78;
	private int term79;
	private int term80;

}
